service: nuxt-serverless-template
package:
  exclude:
    - src/**
    - aws.config.js
    - aws.config.example.js
    - README.md
    - yarn-error.log

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-northeast-2
  environment:
    NODE_ENV: production

functions:
  NuxtRenderingFunction:
    handler: handler.render
    memorySize: 2048
    timeout: 30
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline